version: "3"

services:

  backend:
    build: ./backend
    container_name: campus_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/campus
      - JWT_SECRET=campus_secret
    restart: always

  frontend:
    build: ./frontend
    container_name: campus_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend